### ISSUE TITLE
nullable field does not accept None as default

### ISSUE THREAD

**Issue by fspegni** [anthony-tresontani/django-adaptors#18]
in the `fields.py` the method `get_prep_value` contains the following code:

    ...
            if not value and self.null and self.default is not None:
                value = self.default
            else:
                value = self.to_python(value)

    ...

this generates an exception in the following scenario:
- the field is a `DateField`
- the field is marked as `null=True` and has `default=None`

but I would expect it to not generate any exception: I simply desire to have a datefield which is null if not specified in the csv file. at the moment I patched the code as follows:

            if not value and self.null:
                value = self.default
            else:
                value = self.to_python(value)

which behaves as I expect. I thought you may desire to have it in your code, as I didn't find any other way to specify that a DateField can be optional in the csv file.

**Comment by molecular** [comment]
arghhh! After hours of having this problem we just discovered the **identical fix**. Lol.

So I second this!

Is this project maintained?

**Comment by molecular** [comment]
So I made Pull Request #21. @anthony-tresontani, can you please consider and pull it?
